version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: "daily"
    groups:
      development-dependencies:
        dependency-type: "development"
